[build]
  command   = "mkdir -p netlify/functions/bin && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o netlify/functions/bin/yt-dlp && chmod +x netlify/functions/bin/yt-dlp"
  publish   = "."

[functions]
  directory      = "netlify/functions"
  included_files = ["netlify/functions/bin/**"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
