[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  function = "proxy"
  path = "/download-proxy"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
