[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[edge_functions]
  directory = "netlify/edge-functions"

[[edge_functions]]
  function = "proxy"
  path = "/.netlify/edge-functions/proxy"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
